### ISSUE TITLE
Works for URLs, Not for music on local drive.

### ISSUE THREAD

**Issue by yarub123** [vitorgalvao/watch-list-workflow#1]
### Workflow version

2023.3

### Alfred version

5.1

### macOS version

13.4.1 Ventura

### Debugger output

```alfred_debugger
ERROR: Watch List[Run Script] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - mediainfo (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:159:in `popen2'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:342:in `capture2'
```

### More details

<img width="797" alt="image" src="https://github.com/vitorgalvao/watch-list-workflow/assets/84487964/1561beee-f647-4af1-a6db-260832c880a3">

I'm assuming I gotta do something with Ruby, or fix the directory or something, though my other Ruby workflows work fine. Thanks in advance Victor. Love your workflows ❤️

**Comment by vitorgalvao** [comment]
You are missing a dependency (`mediainfo`). Run [Resolve Dependencies](https://www.alfredapp.com/help/kb/dependencies/) to install it.

**Comment by yarub123** [comment]
It's wild that in all these years of Alfred usage I had no clue this option
existed 🤦‍♂️🤦‍♂️. Thank you, good sir. You're fuckin awesome.

**Comment by vitorgalvao** [comment]
> I had no clue this option existed

It’s new with Alfred 5 and the Gallery.
